name 'tmont-rethinkdb'
version '0.1.0'
source 'https://github.com/tmont/puppet-rethinkdb'
author 'tmont'
license 'MIT'
summary 'Puppet RethinkDB management module'
description 'This module can be used for basic RethinkDB installation and management'
project_page 'https://github.com/tmont/puppet-rethinkdb'

dependency 'puppetlabs/stdlib', '>= 4.3.2'
dependency 'puppetlabs/apt', '>= 1.6.0'
